// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujltdkehetooiasqhxmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqbHRka2VoZXRvb2lhc3FoeG1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3Njg4NDQsImV4cCI6MjA3MDM0NDg0NH0.hpTV0hSh8BV9YYYAM463TpuLMmQKvLaCT-9JPbnaD_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});